### ISSUE TITLE
How to publish 2XX, 4XX response metric to cloud watch

### ISSUE THREAD

**Issue by harshjn04** [Nordstrom/artillery-plugin-cloudwatch#11]
Only Result latency is published to cloudwatch, How to check metrics for 2XX and 4XX response count in cloud watch
Example 
START RequestId: 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 Version: $LATEST
2020-01-29T09:16:25.289Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Starting Artillery...
2020-01-29T09:16:25.780Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Started phase 0 (Max load), duration: 120s @ 09:16:25(+0000) 2020-01-29
2020-01-29T09:16:35.828Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Metrics reported to CloudWatch
2020-01-29T09:16:35.842Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Report @ 09:16:35(+0000) 2020-01-29
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Scenarios launched: 249
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Scenarios completed: 231
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Requests completed: 231
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO RPS sent: 25.41
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Request latency:
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO min: 6.1
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO max: 8716.5
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO median: 11.3
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO p95: 4203
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO p99: 7703.8
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Codes:
**2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO 200: 53**
**2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO 400: 175**
2020-01-29T09:16:35.843Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO 424: 3
2020-01-29T09:16:35.844Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO undefined
2020-01-29T09:16:45.821Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Metrics reported to CloudWatch
2020-01-29T09:16:45.822Z 1c5dafe5-69d0-4b11-9ffc-30e7e53ded98 INFO Report @ 09:16:45(+0000) 2020-01-29

Also the result latency is grouped under "Metrics with no dimensions".

**Comment by kanagas3** [comment]
did this issue resolved?

**Comment by itkq** [comment]
I implemented to collect additional metrics in forked branch https://github.com/itkq/artillery-plugin-cloudwatch/commits/master. I also changed the implementation and the name of the latency metric a bit. But I'm not sure if it is better to make a patch to this repository because it doesn't seem to be actively maintained.

![image](https://user-images.githubusercontent.com/8341422/75042659-1ba03080-5502-11ea-8605-e918dc83d2d8.png)

**Comment by konyu** [comment]
@erikerikson How do you think about this issue?

**Comment by kwhitejr** [comment]
@itkq Really like the look of your fork, Takuya. I've been wanting to get more of the metrics into CloudWatch as well, not just average latency. Gonna try out your code soon!

Doesn't seem like CloudWatch is Nordstrom's main tech, so you're right that it is not actively maintained. But @gwsii was responsive per https://github.com/Nordstrom/artillery-plugin-cloudwatch/pull/14.

**Comment by lkolchin** [comment]
@itkq 
How can I deploy your fork?
I'm getting this in the lambda logs
```
WARNING: plugin cloudwatch specified but module artillery-plugin-cloudwatch could not be loaded
```

I do have this in dependencies:
```
  "dependencies": {
"artillery-plugin-cloudwatch": "git+https://github.com/itkq/artillery-plugin-cloudwatch.git",
.
.
}
```

And I did redeploy the lambda with:
```
slsart deploy --stage stagingtest1
```

My script looks like this:
```
config:
  plugins:
    cloudwatch:
      namespace: "serverless-artillery-stagingtest1"
  # this hostname will be used as a prefix for each URI in the flow unless a complete URI is specified
  target: "https:/"
  # Ramp up arrival rate from 10 to 50 over 2 minutes, followed by 2 minutes at 50 arrivals per second.
  phases:
    - duration: 120
      arrivalRate: 10
      rampTo: 50
      name: "Warm up the application"
    - duration: 120
      arrivalRate: 50
      name: "Sustained max load"
scenarios:
  - name: "Search 1"
    weight: 20
    flow:
      - log: Start 1
      - get:
          url: "/test1.co.nz/test"
      - think: 3
      - get:
          url: "https://www.test2.com.au/test"
      - log: Done 1

  - name: "Search 2"
    weight: 10
    flow:
      - log: Start 2
      - get:
          url: "https://www.test3.com.au/test"
      - log: Done 2
```

Invoking it with:
```
$ slsart invoke -a --stage stagingtest1 -p scripts/script.yml
```
